<?php echo $this->getContent() ?>
<div ng-controller="musicPlayer">
	<div class="panel panel-default">
		<div class="panel-body">
			<form method="post" action="/soundfiles/add_music" enctype="multipart/form-data">
				<input name="userfile" type="file">
				<br>
				<input type="submit" value="Upload" id="registration-button">
			</form>
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-body">
			<div x-musicplayer></div>
		</div>
	</div>

	<div class="panel panel-default">
			<div class="panel-body">
				<div class="input-group">
					<span class="input-group-addon" id="basic-addon3">Search</span>
					<input type="text"  ng-model="search" class="form-control" id="basic-url" aria-describedby="basic-addon3">
				</div>
			</div>

			<div class="panel-body">
				<ul class="list-group">
					<li class="list-group-item" ng-hide="deleted[track.id]"  ng-repeat="track in tracks | filter:search">
						{{track.name}}
						<span class="musicplayer-playlist-options">
							<a href="" ng-click="changeTrack(track)"><span class="glyphicon glyphicon-play"></span></a>
							<a href="" ng-click="deleteTrack(track)"><span class="glyphicon glyphicon-trash"></span></a>
						</span>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
