<?php echo $this->getContent() ?>

<div class="panel panel-default">
	<div class="panel-body">
		<form method="post" action="/soundfiles/add_music" enctype="multipart/form-data">
			<input name="userfile" type="file">
			<br>
			<input type="submit" value="Upload" id="registration-button">
		</form>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-body">


	</div>

	<div class="panel-body">
		<input type="text" ng-model="search">
	</div>
	<table class="table" ng-controller="get_all_tracks">
		<tr ng-repeat="track in tracks | filter:search">
			<td>{{track.name}}</td>
			<td>
				<audio src="{{track.filename}}" controls ></audio>
			</td>
			<td><a href="/soundfiles/delete/{{track.id}}"><span class="glyphicon glyphicon-trash"></span></a></td>
		</tr>
	</table>
</div>
