<?php echo $this->getContent() ?>

<div class="panel panel-default">
	<div class="panel-body">
		<form method="post" action="/users/add_music" enctype="multipart/form-data">
			<input name="userfile" type="file">
			<br>
			<input type="submit" value="Upload" id="registration-button">
		</form>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-body">

		<?php
//		/** @var array $tracks */
//		foreach($tracks as $track){
//			?>
<!--			<div>-->
<!--				--><?php //echo $track['name'] ?>
<!--			</div>-->
<!--			<audio src="/uploads/--><?php //echo $track['filename'] ?><!--" controls ></audio>-->
<!--			<br>-->
<!---->
<!--			--><?php
//		}

		?>

	</div>

	<div class="panel-body">
		<input type="text" ng-model="search">
	</div>
	<table class="table" ng-controller="get_all_tracks">
		<tr ng-repeat="track in tracks | filter:search">
			<td>{{track.name}}</td>
			<td>
				<audio src="{{track.filename}}" controls ></audio>
			</td>
		</tr>
	</table>
</div>
