<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-57298752-1', 'auto');
	ga('send', 'pageview');

</script>
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0">

	<!-- Always force latest IE rendering engine or request Chrome Frame -->
	<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">

	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800">

	<!-- Use title if it's in the page YAML frontmatter -->
	<title>Viechbook</title>

	<link href="/vendor/core-admin-template/stylesheets/application.css" media="screen" rel="stylesheet" type="text/css" />

	<script src="/vendor/core-admin-template/javascripts/application.js" type="text/javascript"></script>
</head>

<body>

<nav class="navbar navbar-default navbar-inverse navbar-static-top" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<a class="navbar-brand" href="#">Viechbook</a>


	</div>

</nav>
<div class="container">

	<div class="col-md-4 col-md-offset-4">
		<div class="pre">
			<?php echo $this->getContent() ?>
		</div>
	</div>


	<div class="row">

		<div class="col-lg-6">
			<h3>Reset Password for User: <?php echo $user->username ?></h3><br>

			<div class="box">
				<div class="box-content">

					<div class="padded">
						<?php echo $this->tag->form([
							'users/reset_password/' . $token,
							'class' => 'form-horizontal fill-up validatable'
						]); ?>


						<div class="form-group">
							<label class="control-label col-lg-2">Password</label>
							<div class="col-lg-10">
								<input type="password" class="validate[required,minSize[6]]" id="password"  name="password" value=""/>
							</div>
						</div>


						<div class="form-group">
							<label class="control-label col-lg-2">Password (repeat)</label>
							<div class="col-lg-10">
								<input type="password" class="validate[required,equals[password],minSize[6]]" name="" value=""/>
							</div>
						</div>


						<div class="form-actions">
							<button type="submit" class="btn btn-blue">Save changes</button>
						</div>
						<?php echo $this->tag->endForm(); ?>

					</div>
				</div>

			</div>
		</div>
	</div>
</div>


</body>
</html>
