<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<?php $this->assets->outputCss() ?>

	<title>Viechbook</title>
</head>
<body>

<div class="container-fluid">

	<div class="col-md-4 col-md-offset-4">
		<div class="pre">
			<?php echo $this->getContent() ?>
		</div>
	</div>


	<div class="row">

		<div class="col-lg-6">
			<h3>Reset Password for User: <?php echo $user->username ?></h3><br>

			<div class="box">
				<div class="box-content">

					<div class="padded">
						<?php echo $this->tag->form([
							'users/reset_password/' . $token,
							'class' => 'form-horizontal fill-up validatable'
						]); ?>


						<div class="form-group">
							<label class="control-label col-lg-2">Password</label>
							<div class="col-lg-10">
								<input type="password" class="validate[required,minSize[6]]" id="password"  name="password" value=""/>
							</div>
						</div>


						<div class="form-group">
							<label class="control-label col-lg-2">Password (repeat)</label>
							<div class="col-lg-10">
								<input type="password" class="validate[required,equals[password],minSize[6]]" name="" value=""/>
							</div>
						</div>


						<div class="form-actions">
							<button type="submit" class="btn btn-blue">Save changes</button>
						</div>
						<?php echo $this->tag->endForm(); ?>

					</div>
				</div>

			</div>
		</div>
	</div>
</div>


</body>
</html>
