/**
 * Created by cite on 14.09.15.
 */
var EMOJI_MAPPING = [
    [':)', 'emojismile'],
    [':(', 'emojifrown'],
    [':P', 'emojitongue'],
    [':D', 'emojigrin'],
    ['=D', 'emojigrin'],
    [':o', 'emojigasp'],
    [';)', 'emojiwink'],
    ['8)', 'emojiglasses'],
    ['8-)', 'emojiglasses'],
    ['B|', 'emojisunglasses'],
    ['>:(', 'emojigrumpy'],
    [':/', 'emojiunsure'],
    [':\'(', 'emojicry'],
    ['3:)', 'emojidevil'],
    ['O:)', 'emojiangel'],
    [':*', 'emojikiss'],
    [':*)', 'emojikiss'],
    ['<3', 'emojiheart'],
    ['^^', 'emojikiki'],
    ['^_^', 'emojikiki'],
    ['-.-', 'emojisquint'],
    ['-_-', 'emojisquint'],
    ['oO', 'emojiconfused'],
    ['oO', 'emojiconfused_rev'],
    ['o.O', 'emojiconfused'],
    ['O.o', 'emojiconfused_rev'],
    ['>:o', 'emojiupset'],
    [':v', 'emojipacman'],
    [':|]', 'emojirobot'],
    [':3', 'emojicolonthree'],
    ['<(")', 'emojipenguin'],
    [':putnam:', 'emojiputnam'],
    ['(^^^)', 'emojishark'],
    ['(y)', 'emojilike'],
    [':poop:', 'emojipoop']
];

