<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">

	<title>Viechbook</title>
</head>



<body>

<nav class="navbar navbar-default navbar-static-top ">
	<div class="container">
		<div class="navbar-header navbar-brand navbar-left" href="#">
			<img style="max-width:100%; max-height:100%;" alt="Brand" src="/img/soundviech.jpg">
		</div>

		<div class="navbar-header navbar-left" style="margin-left: -30px;">
			<a class="navbar-brand">Viechbook</a>
		</div>

		<form class="navbar-header navbar-form " role="search">
			<div class="form-group">
				<input id="general-searchbar" type="text" class="form-control typeahead navbar-left" placeholder="Search">
			</div>
		</form>

		<p class="navbar-text navbar-heade">The Mission Is The Message Is Sound</p>

		<div class="navbar-header navbar-right">
			<button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-envelope"></span></button>
			<button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-time"></span></button>
			<button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-user"></span></button>
		</div>
	</div>
</nav>

<div class="container">
	<div class="col-md-4">
		<h1>Hello, world!</h1>
	</div>

	<div class="col-md-4">
		<h1>Hello, again!</h1>
	</div>

	<div class="col-md-4">
		<h1>Hello, the third!</h1>
	</div>
</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="/vendor/typeahead/js/bootstrap3-typeahead.min.js"></script>
<script src="https://autobahn.s3.amazonaws.com/js/autobahn.min.js"></script>

<script type="text/javascript">
	<?php if(VIECHBOOK_ENV == 'LIVE' ) { ?>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-57298752-1', 'auto');
	ga('send', 'pageview');
	<?php } ?>
</script>

<script type="text/javascript">
	$(document).ready(function() {
		var input = $('.typeahead');

		input.typeahead({
			source: function (query, process) {
				return $.getJSON('/users/list_all', function (response) {
					var preProcessed = [];

					for(var i in response.data) {
						var element = response.data[i]

						preProcessed.push({
							id: element.id,
							name: element.username
						})
					}

					return process(preProcessed);
				});
			},
			autoSelect: true
		});
		/*
		 input.change(function() {
		 var current = input.typeahead("getActive");

		 console.debug(input);
		 if (current) {
		 console.log(current);
		 // Some item from your model is active!
		 if (current.name == input.val()) {
		 // This means the exact match is found. Use toLowerCase() if you want case insensitive match.
		 } else {
		 // This means it is only a partial match, you can either add a new item
		 // or take the active if you don't want new items
		 }
		 } else {
		 // Nothing is active so it is a new value (or maybe empty value)
		 }
		 });*/
	})

</script>

<script type="text/javascript">
	var updateUserMenuNotifications = function() {
		$.getJSON( "/users/get_notifications/" , function( notifications ) {
			var totalNotifications;
			var totalUpdatedConversations = 0;

			$.each( notifications, function(index, notification) {
				if( notification.type == <?= Notifications::TYPE_NEW_MESSAGE ?> ) {
					totalUpdatedConversations++;
				}
			});

			/**
			 * only got these atm
			 * @type {number}
			 */
			totalNotifications = totalUpdatedConversations;

			$("#profile-notification-count").text( totalNotifications > 0 ? totalNotifications : '' );
			$("#profile-conversation-notification-count").text(totalUpdatedConversations > 0 ? totalUpdatedConversations : '');

			/**
			 */
			var title;

			if(totalNotifications > 0) {
				title  = '(' + totalNotifications + ') Viechbook';
			}
			else {
				title = 'Viechbook';
			}

			$(document).prop('title', title);
		});
	};

	var theViech = function() {
		var registrations = [];

		this.register = function(type, callback) {
			registrations.push( {type: type, callback: callback} );
		};

		this.receive = function(message) {
			$.each(registrations, function (index, registration) {
				if( registration.type == message.type ) {
					registration.callback(message);
				}
			});
		};
	};

	var viech;
	var connection;

	$(document).ready( function() {

		viech = new theViech();

		connection = new ab.Session('<?php echo RATCHET_SERVER_ADRESS; ?>',
			function() {
				connection.subscribe('<?= $currentUser['id'] ?>', function(topic, data) {
					viech.receive(data);
					console.log('New article published to category "' + topic + '" : ' + data);
				});

				console.log('Connected to the big viech...');
			},
			function() {
				console.warn('WebSocket connection closed');
			},
			{'skipSubprotocolCheck': true}
		);

		updateUserMenuNotifications();

		/**
		 * @TODO make register take an array instead or both?
		 **/
		viech.register(<?= Notifications::TYPE_NOTIFICATION_CHANGED ?> , function() {
			updateUserMenuNotifications();
		});

		viech.register(<?= Notifications::TYPE_NEW_MESSAGE ?> , function() {
			updateUserMenuNotifications();
		});


	});

</script>

<div class="main-content">
	<div class="container padded">
		<?php echo $this->getContent() ?>
	</div>
</div>


</body>
</html>
