<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<?php use Viechbook\Model\Notifications;

	$this->assets->outputCss() ?>

	<title>Viechbook</title>
</head>

<body>

<div class="chat-containerbar-bottom">
	<div class="panel panel-default chat-conversation-window">
		<div class="glyphicon glyphicon-remove-sign chat-conversation-window-close-button"></div>
		<div class="panel-heading chat-conversation-window-headline">
			Lorem
		</div>
		<div class="panel-body chat-conversation-window-message-containter">
			<div class="chat-message-bubble-left">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. </div>
			<div class="chat-message-bubble-right">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. </div>
			<div class="chat-message-bubble-right">Lorem ipsum</div>
		</div>
		<div"></div>
		<div class="chat-conversation-window-bottom-bar">
			<textarea class="chat-message-editor-textarea"></textarea>
		</div>
	</div>
</div>

<nav class="navbar navbar-default navbar-static-top viechbook-nav-top">
	<div class="container-fluid">
		<div class="navbar-header navbar-brand navbar-left" href="#">
			<img style="max-width:100%; max-height:100%;" alt="Brand" src="/img/soundviech.jpg">
		</div>

		<div class="navbar-header navbar-left">
			<a class="navbar-brand">Viechbook</a>
		</div>

		<form class="navbar-header navbar-form " role="search">
			<div class="form-group">
				<input id="general-searchbar" type="text" class="form-control typeahead navbar-left" placeholder="Search">
			</div>
		</form>

		<!-- <p class="navbar-text">The Mission Is The Message Is Sound</p> -->

		<div class="navbar-header navbar-right">
			<button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-envelope"></span></button>
			<button class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-time"></span></button>

			<div class="btn-group">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<span class="glyphicon glyphicon-off">&nbsp;<span class="caret"></span>
				</button>
				<ul class="dropdown-menu">
					<li><a href="/session/logout">Logout</a></li>
				</ul>
			</div>
		</div>
	</div>
</nav>

<div class="container chat-people">
	<ul class="nav nav-pills nav-stacked">
		<li role="presentation"><a href="#">User1</a></li>
		<li role="presentation"><a href="#">User2</a></li>
		<li role="presentation"><a href="#">User3</a></li>
		<li role="presentation"><a href="#">User3</a></li>
		<li role="presentation"><a href="#">User3</a></li>
		<li role="presentation"><a href="#">User3</a></li>
		<li role="presentation"><a href="#">User3</a></li>
	</ul>
</div>

<div class="container-fluid" style="padding-top:100px ">
	<div class="col-md-2">
		<ul class="list-group">
			<li class="list-group-item"><span class="glyphicon glyphicon-globe"></span>&nbsp;News</li>
			<li class="list-group-item"><span class="glyphicon glyphicon-calendar"></span>&nbsp;Events</li>
			<li class="list-group-item"><span class="glyphicon glyphicon-asterisk"></span>&nbsp;Other</li>
		</ul>
	</div>

	<div class="col-md-8">
		<?php echo $this->getContent() ?>

		<div class="panel panel-default">
			<div class="panel-heading">
				<h4>Hello, world!</h4>
			</div>
			<div class="panel-body">
				Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<h4>Hello, world!</h4>
			</div>
			<div class="panel-body">
				Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<h4>Hello, world!</h4>
			</div>
			<div class="panel-body">
				Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<h4>Hello, world!</h4>
			</div>
			<div class="panel-body">
				Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
			</div>
		</div>		<div class="panel panel-default">
			<div class="panel-heading">
				<h4>Hello, world!</h4>
			</div>
			<div class="panel-body">
				Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<h4>Hello, world!</h4>
			</div>
			<div class="panel-body">
				Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<h4>Hello, world!</h4>
			</div>
			<div class="panel-body">
				Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
			</div>
		</div>

	</div>
</div>

<?php $this->assets->outputJs() ?>

<script type="text/javascript">
	$(document).ready(function() {
		var input = $('.typeahead');

		input.typeahead({
			source: function (query, process) {
				return $.getJSON('/users/list_all', function (response) {
					var preProcessed = [];

					for(var i in response.data) {
						var element = response.data[i]

						preProcessed.push({
							id: element.id,
							name: element.username
						})
					}

					return process(preProcessed);
				});
			},
			autoSelect: true
		});
	});


</script>

<script type="text/javascript">
	var updateUserMenuNotifications = function() {
		$.getJSON( "/users/get_notifications/" , function( notifications ) {
			var totalNotifications;
			var totalUpdatedConversations = 0;

			$.each( notifications, function(index, notification) {
				if( notification.type == <?= Notifications::TYPE_NEW_MESSAGE ?> ) {
					totalUpdatedConversations++;
				}
			});


			totalNotifications = totalUpdatedConversations;

			$("#profile-notification-count").text( totalNotifications > 0 ? totalNotifications : '' );
			$("#profile-conversation-notification-count").text(totalUpdatedConversations > 0 ? totalUpdatedConversations : '');

			var title;

			if(totalNotifications > 0) {
				title  = '(' + totalNotifications + ') Viechbook';
			}
			else {
				title = 'Viechbook';
			}

			$(document).prop('title', title);
		});
	};

	var theViech = function() {
		var registrations = [];

		this.register = function(type, callback) {
			registrations.push( {type: type, callback: callback} );
		};

		this.receive = function(message) {
			$.each(registrations, function (index, registration) {
				if( registration.type == message.type ) {
					registration.callback(message);
				}
			});
		};
	};

	var viech;
	var connection;

	$(document).ready( function() {
		console.debug('wtf');
		viech = new theViech();

		connection = new ab.Session('<?php echo RATCHET_SERVER_ADRESS; ?>',
			function() {
				connection.subscribe('<?= $currentUser['id'] ?>', function(topic, data) {
					viech.receive(data);
					console.log('New article published to category "' + topic + '" : ' + data);
				});

				console.log('Connected to the big viech...');
			},
			function() {
				console.warn('WebSocket connection closed');
			},
			{'skipSubprotocolCheck': true}
		);

		updateUserMenuNotifications();

		viech.register(<?= Notifications::TYPE_NOTIFICATION_CHANGED ?> , function() {
			updateUserMenuNotifications();
		});

		viech.register(<?= Notifications::TYPE_NEW_MESSAGE ?> , function() {
			updateUserMenuNotifications();
		});


	});
</script>

</body>
</html>
